### ISSUE TITLE
Running issue.

### ISSUE THREAD

**Issue by KAWADAKKLT** [EasyRy/CRA-PCN#10]
Hello

I would like to express my appreciation for your excellent work on the paper. I have read it with great interest and found the ideas and findings very valuable.

So, I tried to run your code to help me better understand your approach. Following the steps you provided, I successfully ran the program, but it seems there is an issue with the loss, as follows: 

Epoch 1/400] LearningRate = 0.000050 EpochTime = 1051.690 (s) Losses = ['398.9419', '191.6194', '194.3231', '98.1836', '398.9419']
#1 414553.0261 207221.8087 207268.8722 414553.0261 | 207153.8768 | #0 inf
Saved checkpoint to results/train_pcn_Log_2024_09_21_07_22_16/checkpoints/ckpt-best.pth ...
[Epoch 2/400] LearningRate = 0.000100 EpochTime = 1040.477 (s) Losses = ['249.1492', '148.7280', '192.7548', '48.7980', '249.1492']
#2 413.8713 249.3701 189.6616 413.8713 | 96.1456 | #1 207153.8768
Saved checkpoint to results/train_pcn_Log_2024_09_21_07_22_16/checkpoints/ckpt-best.pth ...
[Epoch 3/400] LearningRate = 0.000150 EpochTime = 1041.626 (s) Losses = ['2141.7472', '1345.0533', '1172.4521', '1425.1828', '2141.7472']
#3 1860.9558 1668.6659 1339.2553 1860.9558 | 2154.5263 | #2 96.1456
[Epoch 4/400] LearningRate = 0.000200 EpochTime = 1042.955 (s) Losses = ['39132.2335', '15720.7370', '15764.4248', '16496.8188', '39132.2335']
#4 3805983.8828 1901836.7156 1901923.7494 3805983.8828 | 1902569.7392 | #2 96.1456
[Epoch 5/400] LearningRate = 0.000250 EpochTime = 1060.114 (s) Losses = ['nan', 'nan', 'nan', 'nan', 'nan']
#5 nan nan nan nan | nan | #2 96.1456
[Epoch 6/400] LearningRate = 0.000300 EpochTime = 1069.615 (s) Losses = ['nan', 'nan', 'nan', 'nan', 'nan']
#6 nan nan nan nan | nan | #2 96.1456
[Epoch 7/400] LearningRate = 0.000350 EpochTime = 1070.290 (s) Losses = ['nan', 'nan', 'nan', 'nan', 'nan']
#7 nan nan nan nan | nan | #2 96.1456
……………………

The loss data seems to be overflowing, but I'm not sure where the problem lies. I haven't changed the code and I'm using the PCN dataset. I ran the command **python train_pcn.py**. The specific configuration environment is 
       Ubuntu 20.04

    python == 3.6.13
    PyTorch == 1.10.1
    CUDA == 11.3
    numpy == 1.19.5
    open3d == 0.9.0.0

Thank you very much for your time and consideration. I look forward to hearing from you.

**Comment by EasyRy** [comment]
Thanks for your interest for our work!
I think you can try:
1. Follow [tips](https://github.com/EasyRy/CRA-PCN/tree/main/models#tips) to increase the constant of interpolation.
2. Use a deconvolution-based seed generator. [here](https://github.com/EasyRy/CRA-PCN/tree/main/models#model-list)

**Comment by KAWADAKKLT** [comment]
Thank you very much for your prompt reply.
