### ISSUE TITLE
[Open3D WARNING] Read PCD failed: unable to open file:

### ISSUE THREAD

**Issue by the-king-of-yhq** [EasyRy/CRA-PCN#12]
How to solve this [Open3D WARNING] Read PCD failed: unable to open file:

**Comment by the-king-of-yhq** [comment]
你好，我无论怎么设置这个os.environ['CUDA_VISIBLE_DEVICES']都没用，都会默认分布，而且还是不均匀的

**Comment by EasyRy** [comment]
第一个问题，可能是文件路径不对？
第二个问题，我看了下你在另一个issue里的截图，我不知道怎么解决。不过看起来，这个似乎不影响训练，你可以尝试把batch size拉满？

**Comment by EasyRy** [comment]
Close this issue since no more response. Feel free to reopen it if you have more questions.
