### ISSUE TITLE
Unable to find the  code of 2 CRT modules designed in your paper！

### ISSUE THREAD

**Issue by HenryHoou** [EasyRy/CRA-PCN#2]
Sorry to bother you, but I've read your code carefully.

**Comment by EasyRy** [comment]
1. The code of CRT can be found in **crapcn.py**:
https://github.com/EasyRy/CRA-PCN/blob/7051c0050cab6e16730dcbe569c430eb89fcc0da/crapcn.py#L88
The  Intra- and inter-level CRT share the same implementation, and the implementation is consistent with the paper. 

2. You mean CRT is similar with Upsample Transformer in SeedFormer?  In my opinion, Upsample Transformer is used for point generation in the local aggregation manner, while our CRT is used to extract multi-scale features.

3. The overall architecture of CRA-PCN is similar with SnowflakeNet and SeedFormer, but we argue that our model is **not** a cutdown version of SeedFormer.

**Comment by hhy2001** [comment]
Thank you for such a prompt reply, I started reading from model.py, which is a bit misleading.It has solved my problem by following your prompts. 
My statement may not be accurate, and I have not doubted your work.I mean to marvel at how you have achieved such an amazing indicator with such a small number of parameters, which is worth learning! The number of parameters of the model you proposed is more than ten times less than that of AdapoinTr!  Hope to see more work from you in this field.

**Comment by hhy2001** [comment]
Thank you for such a prompt reply, I started reading from model.py, which is a bit misleading.It has solved my problem by following your prompts.
My statement may not be accurate, and I have not doubted your work.I mean to marvel at how you have achieved such an amazing metircs  with such a small number of parameters, which is worth learning! The number of parameters of the model you proposed is more than ten times less than that of AdapoinTr! Hope to see more work from you in this field.

**Comment by EasyRy** [comment]
Thanks for your interest! We will continuously optimize this repo.
