### ISSUE TITLE
测试本地数据

### ISSUE THREAD

**Issue by yangfeng-Lyu** [EasyRy/CRA-PCN#4]
作者，您好！
        很感谢你们的出色工作！我想请教如何在你们的工作中使用本地数据，例如使用本地数据进行训练或者测试？

**Comment by EasyRy** [comment]
您好，感谢您的关注！

我们提供了一个使用预训练好的模型推理本地点云的例子：[infer.py](https://github.com/EasyRy/CRA-PCN/blob/main/infer.py)。

如果您想训练自己的数据集，可以考虑将其转换成MVP的格式，然后通过修改[train_mvp.py](https://github.com/EasyRy/CRA-PCN/blob/main/train_mvp.py) 和 [test_mvp.py](https://github.com/EasyRy/CRA-PCN/blob/main/test_mvp.py)中的数据路径进行训练。

**Comment by yangfeng-Lyu** [comment]
作者，您好！
我尝试使用模型推理本地点云，但效果并不理想。补全点云似乎偏离了预期。推理的点云数量必须是2048吗？我的点云结构是类似于台柱的对称物体，一下是我的结果
![Uploading Snipaste_2024-03-13_09-35-15.jpg…]()

**Comment by EasyRy** [comment]
您的图片我看不到？是上传错了吗？

我们的模型是在PCN数据集上训练的，所以在推理时，要使用和PCN数据集尺度差不多的点云，可以参考example_pc里的air.ply的大小。

点数的话，也不一定得是2048吧。

**Comment by EasyRy** [comment]
Close this issue since no more responses. If you have more problems, feel free to reopen it.
