### ISSUE TITLE
PCN数据集单，双显卡训练问题

### ISSUE THREAD

**Issue by 864479373** [EasyRy/CRA-PCN#7]
作者您好，我在双显卡上训练PCN，chamfer distance指标无论是哪两个点云之间进行计算(尝试过随机生成点云)，得到的结果张量里的值都全为0，但缩小训练集在单显卡跑的时候chamfer distance值是正常的，请问您出现过这种问题吗

**Comment by EasyRy** [comment]
您好，我们没碰到过这个问题，我们是多显卡训练的。

**Comment by 864479373** [comment]
在我的尝试中，在两张V100卡会出现这种问题，缩小了batch size 和 learning rate 在两张3090卡上进行训练，问题又不存在了。我会再查找问题所在。谢谢您的回复！

**Comment by EasyRy** [comment]
不客气～
