### ISSUE TITLE
本地数据集训练问题

### ISSUE THREAD

**Issue by xingjinderhuoche** [EasyRy/CRA-PCN#9]
请问下作者，在自己本地的数据集上训练时，训练过程中常常在第20轮后损失全是 ‘nan’，本数据集较小（一类，400个，每个40‘原文8-》40’），该方法对小数据集是不是较难训练呢

**Comment by EasyRy** [comment]
你好！您可以尝试下以下做法：
1.我们参考了以往的一些方法(e.g., SnowflakeNet, SeedFormer) ，20轮之前有个warm up的过程，学习率会从一个较小值开始逐步上升至1e-3。您可以试下关闭warm up或者调低学习率；
2.检查下数据集里点云的尺度是否一致；
3.微调预训练好的模型。

**Comment by xingjinderhuoche** [comment]
好嘞！我的这个问题和之前训练出nan的类似，调整下常数项应该可以。
另外还有一个系数，在我的模型里输入点数约为是1576，输出（真实gt）点数约为2048，这边系数可以朝着哪个方向调整呀
  __C.NETWORK.UPSAMPLE_FACTORS                     = [2, 2, 1, 8] # 16384
  __C.NETWORK.KP_EXTENTS                           = [0.1, 0.1, 0.05, 0.025] # 16384

**Comment by EasyRy** [comment]
根据你的输入和输出分辨率，可以直接参考mvp数据集上使用的模型。模型的超参数在models里直接调。我们用的两个upsampling block，上采样率分别为[1, 4]，您可以尝试增加block数量，比如[1, 1, 4]或[1, 2, 2]。
(您列出的两个参数是冗余的，我们没有用到，抱歉引起误解。)

**Comment by xingjinderhuoche** [comment]
谢谢您这两天的回复，已经解决啦
